spring:
  application:
    name: mud-microservice-gatway-web
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# Remote service load balance strategy for Ribbon invoke
mud-microservice-customer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
mud-microservice-activity:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule